openapi: 3.0.0
info:
  title: Teamspeak
  description: Teamspeak WebQuery
  version: 3.12.0
servers:
  - url: http://{host}:{port}/{serverId}
    variables:
      host:
        default: 127.0.0.1
        description: Host of the Teamspeak WebQuery server
      port:
        default: "10080"
        description: HTTP port that WebQuery is bound to
      serverId:
        default: "1"
        description: ID of the server to manipulate
paths:
  /channellist:
    get:
      operationId: channelList
      tags:
        - Channel
      summary: Gets list of channels
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                title: ChannelListResponse
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        channel_name:
                          type: string
                        channel_needed_subscribe_power:
                          type: string
                        channel_order:
                          type: string
                        cid:
                          type: string
                  status:
                    type: object
                    properties:
                      code:
                        type: number
                      message:
                        type: string

  /channelcreate:
    post:
      operationId: channelCreate
      tags:
        - Channel
      summary: Create a new channel
      parameters:
        - name: channel_name
          in: query
          description: Channel's name
          required: true
          schema:
            type: string
        - name: channel_topic
          in: query
          description: Channel's topic
          schema:
            type: string
      responses:
        "200":
          description: Successful
