openapi: 3.0.0
info:
  title: Teamspeak
  description: Teamspeak WebQuery
  version: 3.12.0
servers:
  - url: http://{host}:{port}/{serverId}
    variables:
      host:
        default: 127.0.0.1
        description: Host of the Teamspeak WebQuery server
      port:
        default: "10080"
        description: HTTP port that WebQuery is bound to
      serverId:
        default: "1"
        description: ID of the server to manipulate
paths:
  /channelinfo:
    get:
      operationId: channelInfo
      tags:
        - Channel
      summary: Get info about a channel
      parameters:
        - name: cid
          in: query
          description: Channel ID
          required: true
          schema:
            type: string
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                title: ChannelInfoResponse
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        channel_name:
                          type: string
                        channel_topic:
                          type: string
                        channel_description:
                          type: string
                        channel_flag_permanent:
                          type: string
                          enum: ["0", "1"]
                  status:
                    $ref: "#/components/schemas/Status"
  /channelcreate:
    post:
      operationId: channelCreate
      tags:
        - Channel
      summary: Create a new channel
      parameters:
        - name: channel_name
          in: query
          description: Channel's name
          required: true
          schema:
            type: string
        - name: channel_topic
          in: query
          description: Channel's topic
          schema:
            type: string
        - name: channel_description
          in: query
          description: Channel description
          schema:
            type: string
        - name: channel_flag_permanent
          in: query
          description: Mark channel as permanent
          schema:
            type: string
            enum: ["0", "1"]
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                title: ChannelCreateResponse
                type: object
                properties:
                  body:
                    type: array
                    items:
                      type: object
                      properties:
                        cid:
                          type: string
                  status:
                    $ref: "#/components/schemas/Status"
  /channeledit:
    post:
      operationId: channelEdit
      tags:
        - Channel
      summary: Edit channel
      parameters:
        - name: cid
          in: query
          description: Channel ID
          required: true
          schema:
            type: string
        - name: channel_name
          in: query
          description: Channel name
          schema:
            type: string
        - name: channel_topic
          in: query
          description: Channel topic
          schema:
            type: string
        - name: channel_description
          in: query
          description: Channel description
          schema:
            type: string
        - name: channel_flag_permanent
          in: query
          description: Mark channel as permanent
          schema:
            type: string
            enum: ["0", "1"]
        - name: channel_codec_quality
          in: query
          description: Codec quality for the channel
          schema:
            type: number
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MinimalResponse"
  /channeldelete:
    post:
      operationId: channelDelete
      tags:
        - Channel
      summary: Delete channel
      parameters:
        - name: cid
          in: query
          description: Channel ID
          required: true
          schema:
            type: string
        - name: force
          in: query
          description: Force the deletion
          schema:
            type: number
            enum: [0, 1]
      responses:
        "200":
          description: Successful
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/MinimalResponse"
components:
  schemas:
    MinimalResponse:
      type: object
      properties:
        status:
          $ref: "#/components/schemas/Status"
    Status:
      type: object
      properties:
        code:
          type: number
        message:
          type: string
