/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ChannelListResponseStatus struct for ChannelListResponseStatus
type ChannelListResponseStatus struct {
	Code float32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
