/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// ChannelCreateResponseBody struct for ChannelCreateResponseBody
type ChannelCreateResponseBody struct {
	Cid string `json:"cid,omitempty"`
}
