/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// ChannelListResponse struct for ChannelListResponse
type ChannelListResponse struct {
	Body []ChannelListResponseBody `json:"body,omitempty"`
	Status Status `json:"status,omitempty"`
}
