/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// ChannelCreateResponse struct for ChannelCreateResponse
type ChannelCreateResponse struct {
	Body []ChannelCreateResponseBody `json:"body,omitempty"`
	Status Status `json:"status,omitempty"`
}
