/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// ChannelInfoResponse struct for ChannelInfoResponse
type ChannelInfoResponse struct {
	Body []ChannelInfoResponseBody `json:"body,omitempty"`
	Status Status `json:"status,omitempty"`
}
