/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// MinimalResponse struct for MinimalResponse
type MinimalResponse struct {
	Status Status `json:"status,omitempty"`
}
