/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ChannelDeleteResponse struct for ChannelDeleteResponse
type ChannelDeleteResponse struct {
	Status Status `json:"status,omitempty"`
}
