/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package teamspeak
// Status struct for Status
type Status struct {
	Code float32 `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
