/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200 struct for InlineResponse200
type InlineResponse200 struct {
	Body []InlineResponse200Body `json:"body,omitempty"`
	Status InlineResponse200Status `json:"status,omitempty"`
}
