/*
 * Teamspeak
 *
 * Teamspeak WebQuery
 *
 * API version: 3.12.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// InlineResponse200Status struct for InlineResponse200Status
type InlineResponse200Status struct {
	Code string `json:"code,omitempty"`
	Message string `json:"message,omitempty"`
}
